### ISSUE TITLE
issue with get_options throwing segmetation fault

### ISSUE THREAD

**Issue by maliknajjar** [aQaTL/sane-scan#3]
a bug happens when i exeute this line `let device_options = handle.get_options().unwrap();`
it shows me a `Segmentation fault (core dumped)` error
this is the device I use 
`device `smfp:usb;03f0;f22a;CNB3M429L0' is a HP HP Laser MFP 131 133 135-138 on USB Scanner`
do you have any Idea how to fix this probleme?

**Comment by Xtrem532** [comment]
Its already fixed in the main branch, but has not been published to crates.io.
(As I found out after >3h of debugging 😡)

**Comment by maliknajjar** [comment]
nice .. I added the crate using the git url in Cargo.toml and fixed the problem
```toml
sane-scan = { git = "https://github.com/aQaTL/sane-scan" }
```
thanks a lot

**Comment by aQaTL** [comment]
Thanks @Xtrem532 for pointing that out. I completely forgot to publish a new version. 
Did that just now. Version 0.1.2 is out.
